### PR TITLE
perf(build) let's make building 1ms faster

### PR DESCRIPTION
**Pull request by billymcintosh**
We all know true === 1.    Fuck transcribing.   Fuck bools.   Fuck your bitwise operators.    1 is true. 

This will also help with angular-cli and webpack.   We're looking at a build speed increase.

### CODE REVIEW

**Review by billymcintosh — COMMENTED** [review]
Yes, I can see where you are coming from in this pull request and merge request.  It's interesting you lose the semi-colon.  Is this because Poland or because something else?  

1 is a good bit for a truthy and I would accept this as an improvement.  Unfortunately it's more difficult to improve Billy himself.  Sure, he'll be Scottish, but he'll always be a cunt.  

Good luck with this open sauce.

**Comment by aalstes** [comment]
Every millisecond saved means more time to drink.

**Comment by billymcintosh** [comment]
There's a PR for that, @aalstes https://github.com/intellix/is-billy-scottish/pull/4/commits/d6b1aa4d2c2c902df202f70d8d6643671e4654b9

**Review by billymcintosh — COMMENTED** [review]
Y no merge?

**Pull request closed without merging**
